site_name: PyCript Docs
theme:
  name: material
  logo: https://i.ibb.co/RD2rP3V/Py-Cript-Banner-Room.png
  favicon: https://img.icons8.com/dusk/64/000000/security.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.sections
    - navigation.tracking
    - navigation.instant
    - navigation.indexes 
    - toc.follow
    - content.tabs.link
    

nav:
    - Home: index.md
    - Prerequisites: Prerequisites.md
    - Installation: installation.md
    - Workflow: workflow.md
    - Select Language: Select-Language.md
    - Usage Examples: Examples.md
    - Writing Custom Scripts: Scripts.md
    
    
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower


extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/ano_f_
    - icon: fontawesome/brands/github 
      link: https://github.com/Anof-cyber/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sourav-kalal
    - icon: fontawesome/brands/medium 
      link: https://medium.com/@Ano_F_
    - icon: fontawesome/brands/youtube
      link: https://youtu.be/J8KE5VR8yDk?si=C97g0DH5cCoUGj0e

repo_url: https://github.com/Anof-cyber/PyCript
repo_name: Anof-cyber/PyCript
